// app/layout.tsx
import type { Metadata } from "next"
import { Geist_Mono } from "next/font/google"
import Header from "./components/Header"

const geistMono = Geist_Mono({
  variable: "--geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${geistMono.variable}`}>
      <body className="antialiased">
        <Header />
        {children}
      </body>
    </html>
  )
}
